runtime: nodejs12

env_variables: 
  PORT: 3000
  SMTP_HOST: "localhost"
  SMTP_PORT: 25
  SMTP_SSL: false
  URL: "https://examadmin-backend.appspot.com/"
  SERVER_EMAIL: "postmaster@localhost"
  EMAIL_PASS: "123456@localhost"
  MONGO_CONN_STR: "mongodb+srv://Admin:NrKG9DkvgHhpm5Jm@examadmin-livetest-tmvty.gcp.mongodb.net/test?retryWrites=true&w=majority"
  JWT_SECRET: "MIGrAgEAAiEAvwzN7rDBIe7D2kk3xIA6cKcDmLIc4uW3onudEG2be9ECAwEAAQIhALVc7Gl49f7GcLpZ40zxBYefuoRB1qC4PEH7ew2GGdOBAhEA/fu1sPvBYEE965VfIdKM2QIRAMCRKm2b8JnHCMt1298da7kCEBiY5wjD6P90chW9up/g70kCEFfOGXWPRF8qJTV40T/kD2kCEQCgk8BL1FMeyjD6Nbl7IJX7"
  JWT_EXPIRE: 7200
  MAX_FILESIZE: 5242880
  enableClubs: false

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10